### PR TITLE
Switch from readthedocs to mkdocs (#1432)

### PR DESCRIPTION
**Pull request by raylim**

### CODE REVIEW

**Comment by raylim** [comment]
A few notes:

* I merged the two github actions yaml files into one that handles both build and release (fixed a bug with caching)
* I changed to symlinks for the tutorials instead of the previous workaround
* There's some random job failures with the unit tests (re-trying the build a couple times seems to do the trick)
* I converted rst files to markdown as rst isn't supported by mkdocs

**Comment by raylim** [comment]
Another note: the CLI documentation looks a bit off due to this outstanding bug: https://github.com/DataDog/mkdocs-click/issues/59

**Comment by armaank** [comment]
I made a minor change to fix the navigation heading for the 'publication' page, and also symlink-ed `index.md` in the docs to `README.md`, so that they are always in sync. Only issue is that the logo href in the github `README.md` can't be a relative path, so once this branch is merged into dev, the path can be updated (it's currently referring to a logo in a branch from ages ago)

**Review by armaank — APPROVED** [review]
This looks great. The auto-generated api docs are now visible and readable on the doc site. It'll be much easier to read, update and fix the documentation this way. The navigation is also improved. 

For next steps on this front, I think we'll just need to have a discussion about the look. Right now we're using the default theme, so there is room for experimentation if we want. 
Regarding [the formatting on the existing doc strings](https://github.com/msk-mind/luna/pull/345#issuecomment-1371136201), let's leave them be for now and pick them off later, it isn't urgent (ideally an improved cli runner won't require additional characters like that, a discussion for later).

**Comment by raylim** [comment]
squashed some commits

**Pull request merged**
